public class JazzHRSingleApplicantWrapper {
	/*
    public Applicant applicant;
    public class Applicant{
        public string id;
        public string first_name;
        public string last_name;
        public string email;
        public string address;
        public string location;
        public integer phone;
        public string linkedin_url;
        public string eeo_gender;
        public string eeo_race;
        public string eeo_disability;
        public string website;
        public string desired_salary;
        public date desired_start_date;
        public string referrer;
        public string languages;
        public string wmyu;
        public string has_driver_license;
        public string willing_to_relocate;
        public string citizenship_status;
        public string education_level;
        public string has_cdl;
        public string over_18;
        public string can_work_weekends;
        public string can_work_evenings;
        public string can_work_overtime;
        public string has_felony;
        public string felony_explanation;
        public string twitter_username;
        public string college_gpa;
        public string college;
        public string references;
        public string notes;
        public date apply_date;
        public string comments_count;
        public string source;
        public string recruiter_id;
        public string eeoc_veteran;
        public string eeoc_disability;
        public string eeoc_disability_signature;
        public string eeoc_disability_date;
        public string resume_link;
        //public string comments;
        
    }*/
}